import aiohttp
from _typeshed import Incomplete
from google.auth import exceptions as exceptions, transport as transport
from google.auth.transport import requests as requests

class _CombinedResponse(transport.Response):
    def __init__(self, response) -> None: ...
    @property
    def status(self): ...
    @property
    def headers(self): ...
    @property
    def data(self): ...
    async def raw_content(self): ...
    async def content(self): ...

class _Response(transport.Response):
    def __init__(self, response) -> None: ...
    @property
    def status(self): ...
    @property
    def headers(self): ...
    @property
    def data(self): ...

class Request(transport.Request):
    session: Incomplete
    def __init__(self, session=None) -> None: ...
    async def __call__(self, url, method: str = 'GET', body=None, headers=None, timeout=..., **kwargs): ...

class AuthorizedSession(aiohttp.ClientSession):
    credentials: Incomplete
    def __init__(self, credentials, refresh_status_codes=..., max_refresh_attempts=..., refresh_timeout=None, auth_request=None, auto_decompress: bool = False, **kwargs) -> None: ...
    async def request(self, method, url, data=None, headers=None, max_allowed_time=None, timeout=..., auto_decompress: bool = False, **kwargs): ...
