from google.auth import environment_vars as environment_vars, exceptions as exceptions

CONTEXT_AWARE_METADATA_PATH: str
CERTIFICATE_CONFIGURATION_DEFAULT_PATH: str

def get_client_ssl_credentials(generate_encrypted_key: bool = False, context_aware_metadata_path=..., certificate_config_path=None): ...
def get_client_cert_and_key(client_cert_callback=None): ...
def decrypt_private_key(key, passphrase): ...
def check_use_client_cert(): ...
def check_parameters_for_unauthorized_response(cached_cert): ...
def call_client_cert_callback(): ...
