import grpc
from google.auth import exceptions as exceptions
from google.oauth2 import service_account as service_account

class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
    def __init__(self, credentials, request, default_host=None) -> None: ...
    def __call__(self, context, callback) -> None: ...

def secure_authorized_channel(credentials, request, target, ssl_credentials=None, client_cert_callback=None, **kwargs): ...

class SslCredentials:
    def __init__(self) -> None: ...
    @property
    def ssl_credentials(self): ...
    @property
    def is_mtls(self): ...
