from google.auth import exceptions as exceptions

def has_default_client_cert_source(include_context_aware: bool = True): ...
def default_client_cert_source(): ...
def default_client_encrypted_cert_source(cert_path, key_path): ...
def should_use_client_cert(): ...
