import requests
import requests.adapters
import types
from _typeshed import Incomplete
from google.auth import exceptions as exceptions, transport as transport
from google.oauth2 import service_account as service_account

class _Response(transport.Response):
    def __init__(self, response) -> None: ...
    @property
    def status(self): ...
    @property
    def headers(self): ...
    @property
    def data(self): ...

class TimeoutGuard:
    remaining_timeout: Incomplete
    def __init__(self, timeout, timeout_error_type=...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class Request(transport.Request):
    session: Incomplete
    def __init__(self, session: requests.Session | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, url, method: str = 'GET', body=None, headers=None, timeout=..., **kwargs): ...

class _MutualTlsAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, cert, key) -> None: ...
    def init_poolmanager(self, *args, **kwargs) -> None: ...
    def proxy_manager_for(self, *args, **kwargs): ...

class _MutualTlsOffloadAdapter(requests.adapters.HTTPAdapter):
    signer: Incomplete
    def __init__(self, enterprise_cert_file_path) -> None: ...
    def init_poolmanager(self, *args, **kwargs) -> None: ...
    def proxy_manager_for(self, *args, **kwargs): ...

class AuthorizedSession(requests.Session):
    credentials: Incomplete
    def __init__(self, credentials, refresh_status_codes=..., max_refresh_attempts=..., refresh_timeout=None, auth_request=None, default_host=None) -> None: ...
    def configure_mtls_channel(self, client_cert_callback=None) -> None: ...
    def request(self, method, url, data=None, headers=None, max_allowed_time=None, timeout=..., **kwargs): ...
    @property
    def is_mtls(self): ...
    def close(self) -> None: ...
