import types
from _typeshed import Incomplete
from google.auth import exceptions as exceptions, transport as transport
from google.oauth2 import service_account as service_account

RequestMethods: Incomplete

class _Response(transport.Response):
    def __init__(self, response) -> None: ...
    @property
    def status(self): ...
    @property
    def headers(self): ...
    @property
    def data(self): ...

class Request(transport.Request):
    http: Incomplete
    def __init__(self, http) -> None: ...
    def __call__(self, url, method: str = 'GET', body=None, headers=None, timeout=None, **kwargs): ...

class AuthorizedHttp(RequestMethods):
    http: Incomplete
    credentials: Incomplete
    def __init__(self, credentials, http=None, refresh_status_codes=..., max_refresh_attempts=..., default_host=None) -> None: ...
    def configure_mtls_channel(self, client_cert_callback=None): ...
    def urlopen(self, method, url, body=None, headers=None, **kwargs): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...
    def __del__(self) -> None: ...
    @property
    def headers(self): ...
    @headers.setter
    def headers(self, value) -> None: ...
