from google.auth import exceptions as exceptions, jwt as jwt

async def jwt_grant(request, token_uri, assertion, can_retry: bool = True): ...
async def id_token_jwt_grant(request, token_uri, assertion, can_retry: bool = True): ...
async def refresh_grant(request, token_uri, refresh_token, client_id, client_secret, scopes=None, rapt_token=None, can_retry: bool = True): ...
