from google.auth import credentials as credentials, exceptions as exceptions, jwt as jwt, metrics as metrics, transport as transport

def jwt_grant(request, token_uri, assertion, can_retry: bool = True): ...
def call_iam_generate_id_token_endpoint(request, iam_id_token_endpoint, signer_email, audience, access_token, universe_domain=...): ...
def id_token_jwt_grant(request, token_uri, assertion, can_retry: bool = True): ...
def refresh_grant(request, token_uri, refresh_token, client_id, client_secret, scopes=None, rapt_token=None, can_retry: bool = True): ...
