from _typeshed import Incomplete
from typing import Literal, Sequence
from google.auth import credentials as credentials, exceptions as exceptions, metrics as metrics
from google.oauth2 import reauth as reauth

class Credentials(credentials.CredentialsWithRegionalAccessBoundary, credentials.ReadOnlyScoped, credentials.CredentialsWithQuotaProject):
    token: str | None  # TODO: Can it be None?
    expiry: Incomplete
    def __init__(self, token, refresh_token=None, id_token=None, token_uri=None, client_id=None, client_secret=None, scopes=None, default_scopes=None, quota_project_id=None, expiry=None, rapt_token=None, refresh_handler=None, enable_reauth_refresh: bool = False, granted_scopes=None, trust_boundary=None, universe_domain=..., account=None) -> None: ...
    @property
    def refresh_token(self) -> str|None: ...
    @property
    def scopes(self) -> Sequence[str]|None: ...
    @property
    def granted_scopes(self) -> Sequence[str]|None: ...
    @property
    def token_uri(self)->str|None: ...
    @property
    def id_token(self)->str|None: ...
    @property
    def client_id(self)->str|None: ...
    @property
    def client_secret(self) -> str|None  :
    @property
    def requires_scopes(self) -> Literal[False]: ...
    @property
    def rapt_token(self): ...
    @property
    def refresh_handler(self): ...
    @refresh_handler.setter
    def refresh_handler(self, value) -> None: ...
    @property
    def account(self): ...
    def get_cred_info(self): ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    def with_account(self, account): ...
    def with_universe_domain(self, universe_domain): ...
    @classmethod
    def from_authorized_user_info(cls, info, scopes=None): ...
    @classmethod
    def from_authorized_user_file(cls, filename, scopes=None): ...
    def to_json(self, strip=None): ...

class UserAccessTokenCredentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, account=None, quota_project_id=None) -> None: ...
    def with_account(self, account): ...
    def with_quota_project(self, quota_project_id): ...
    token: Incomplete
    def refresh(self, request) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...
