from google.auth import environment_vars as environment_vars, exceptions as exceptions, jwt as jwt, transport as transport
from typing import Any, Mapping

def verify_token(id_token: str | bytes, request: transport.Request, audience: str | list[str] | None = None, certs_url: str = ..., clock_skew_in_seconds: int = 0) -> Mapping[str, Any]: ...
def verify_oauth2_token(id_token, request, audience=None, clock_skew_in_seconds: int = 0): ...
def verify_firebase_token(id_token, request, audience=None, clock_skew_in_seconds: int = 0): ...
def fetch_id_token_credentials(audience, request=None): ...
def fetch_id_token(request, audience): ...
