from _typeshed import Incomplete
from google.auth import credentials as credentials, exceptions as exceptions, iam as iam, jwt as jwt, metrics as metrics

class Credentials(credentials.Signing, credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri, credentials.CredentialsWithRegionalAccessBoundary):
    def __init__(self, signer, service_account_email, token_uri, scopes=None, default_scopes=None, subject=None, project_id=None, quota_project_id=None, additional_claims=None, always_use_jwt_access: bool = False, universe_domain=..., trust_boundary=None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename, **kwargs): ...
    @property
    def service_account_email(self): ...
    @property
    def project_id(self): ...
    @property
    def requires_scopes(self): ...
    def with_scopes(self, scopes, default_scopes=None): ...
    def with_always_use_jwt_access(self, always_use_jwt_access): ...
    def with_universe_domain(self, universe_domain): ...
    def with_subject(self, subject): ...
    def with_claims(self, additional_claims): ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    def sign_bytes(self, message): ...
    @property
    def signer(self): ...
    @property
    def signer_email(self): ...
    def get_cred_info(self): ...

class IDTokenCredentials(credentials.Signing, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri):
    def __init__(self, signer, service_account_email, token_uri, target_audience, additional_claims=None, quota_project_id=None, universe_domain=...) -> None: ...
    @classmethod
    def from_service_account_info(cls, info, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename, **kwargs): ...
    def with_target_audience(self, target_audience): ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    token: Incomplete
    expiry: Incomplete
    def refresh(self, request) -> None: ...
    @property
    def service_account_email(self): ...
    def sign_bytes(self, message): ...
    @property
    def signer(self): ...
    @property
    def signer_email(self): ...
