from google.oauth2 import utils as utils

class Client(utils.OAuthClientAuthHandler):
    def __init__(self, token_exchange_endpoint, client_authentication=None) -> None: ...
    def exchange_token(self, request, grant_type, subject_token, subject_token_type, resource=None, audience=None, scopes=None, requested_token_type=None, actor_token=None, actor_token_type=None, additional_options=None, additional_headers=None): ...
    def refresh_token(self, request, refresh_token): ...
    def revoke_token(self, request, token, token_type_hint, revoke_url): ...
