from google.oauth2.webauthn_handler import PluginHandler as PluginHandler, WebAuthnHandler as WebAuthnHandler

class WebauthnHandlerFactory:
    handlers: list[WebAuthnHandler]
    def __init__(self) -> None: ...
    def get_handler(self) -> WebAuthnHandler | None: ...
