from google.auth.crypt import base as base

class RSAVerifier(base.Verifier):
    def __init__(self, public_key) -> None: ...
    def verify(self, message, signature): ...
    @classmethod
    def from_string(cls, public_key): ...

class RSASigner(base.Signer, base.FromServiceAccountMixin):
    def __init__(self, private_key, key_id=None) -> None: ...
    @property
    def key_id(self): ...
    def sign(self, message): ...
    @classmethod
    def from_string(cls, key, key_id=None): ...
