from google.auth import environment_vars as environment_vars, exceptions as exceptions

CRYPTOGRAPHY_NOT_FOUND_ERROR: str

def get_agent_identity_certificate_path(): ...
def get_and_parse_agent_identity_certificate(): ...
def parse_certificate(cert_bytes): ...
def calculate_certificate_fingerprint(cert): ...
def should_request_bound_token(cert): ...
def get_cached_cert_fingerprint(cached_cert): ...
