from _typeshed import Incomplete

class LRUCache(dict):
    maxsize: Incomplete
    def __init__(self, maxsize) -> None: ...
    def clear(self) -> None: ...
    def get(self, key, default=None): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def popitem(self): ...
