from google.auth import environment_vars as environment_vars, exceptions as exceptions

CLOUD_SDK_CLIENT_ID: str

def get_config_path(): ...
def get_application_default_credentials_path(): ...
def get_project_id(): ...
def get_auth_access_token(account=None): ...
