from google.auth import environment_vars as environment_vars, exceptions as exceptions

def load_credentials_from_file(filename, scopes=None, quota_project_id=None): ...
def default_async(scopes=None, request=None, quota_project_id=None): ...
