from google.auth import exceptions as exceptions

class _BaseExponentialBackoff:
    def __init__(self, total_attempts=..., initial_wait_seconds=..., randomization_factor=..., multiplier=...) -> None: ...
    @property
    def total_attempts(self): ...
    @property
    def backoff_count(self): ...

class ExponentialBackoff(_BaseExponentialBackoff):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class AsyncExponentialBackoff(_BaseExponentialBackoff):
    def __init__(self, *args, **kwargs) -> None: ...
    def __aiter__(self): ...
    async def __anext__(self): ...
