import logging
from _typeshed import Incomplete
from google.auth import exceptions as exceptions
from typing import Any, Mapping

REFRESH_THRESHOLD: Incomplete

def copy_docstring(source_class): ...
def parse_content_type(header_value): ...
def utcnow(): ...
def utcfromtimestamp(timestamp): ...
def datetime_to_secs(value): ...
def to_bytes(value, encoding: str = 'utf-8'): ...
def from_bytes(value): ...
def update_query(url, params, remove=None): ...
def scopes_to_string(scopes): ...
def string_to_scopes(scopes): ...
def padded_urlsafe_b64decode(value): ...
def unpadded_urlsafe_b64encode(value): ...
def is_python_3(): ...
def is_logging_enabled(logger: logging.Logger) -> bool: ...
def request_log(logger: logging.Logger, method: str, url: str, body: bytes | None, headers: Mapping[str, str] | None) -> None: ...
def response_log(logger: logging.Logger, response: Any) -> None: ...
