from google.auth import _credentials_async, jwt as jwt

def encode(signer, payload, header=None, key_id=None): ...
def decode(token, certs=None, verify: bool = True, audience=None): ...

class Credentials(jwt.Credentials, _credentials_async.Signing, _credentials_async.Credentials): ...
class OnDemandCredentials(jwt.OnDemandCredentials, _credentials_async.Signing, _credentials_async.Credentials): ...
