import threading

class RefreshThreadManager:
    def __init__(self) -> None: ...
    def start_refresh(self, cred, request): ...
    def clear_error(self) -> None: ...

class RefreshThread(threading.Thread):
    def __init__(self, cred, request, **kwargs) -> None: ...
    def run(self) -> None: ...
