import datetime
import google.auth.credentials
import google.auth.transport
import threading
from _typeshed import Incomplete
from google.auth import environment_vars as environment_vars
from typing import NamedTuple

def is_regional_access_boundary_enabled(): ...

DEFAULT_REGIONAL_ACCESS_BOUNDARY_TTL: Incomplete
REGIONAL_ACCESS_BOUNDARY_REFRESH_THRESHOLD: Incomplete
DEFAULT_REGIONAL_ACCESS_BOUNDARY_COOLDOWN: Incomplete
MAX_REGIONAL_ACCESS_BOUNDARY_COOLDOWN: Incomplete

class _RegionalAccessBoundaryData(NamedTuple):
    encoded_locations: str | None
    expiry: datetime.datetime | None
    cooldown_expiry: datetime.datetime | None
    cooldown_duration: datetime.timedelta

class _RegionalAccessBoundaryManager:
    refresh_manager: Incomplete
    def __init__(self) -> None: ...
    def __eq__(self, other): ...
    def enable_blocking_lookup(self) -> None: ...
    def set_initial_regional_access_boundary(self, encoded_locations=None, expiry=None) -> None: ...
    def apply_headers(self, headers) -> None: ...
    def maybe_start_refresh(self, credentials, request) -> None: ...
    def start_blocking_refresh(self, credentials, request) -> None: ...
    def process_regional_access_boundary_info(self, regional_access_boundary_info) -> None: ...

class _RegionalAccessBoundaryRefreshThread(threading.Thread):
    daemon: bool
    def __init__(self, credentials: google.auth.credentials.CredentialsWithRegionalAccessBoundary, request: google.auth.transport.Request, rab_manager: _RegionalAccessBoundaryManager) -> None: ...
    def run(self) -> None: ...

class _RegionalAccessBoundaryRefreshManager:
    def __init__(self) -> None: ...
    def start_refresh(self, credentials, request, rab_manager) -> None: ...
