from google.auth import crypt as crypt, exceptions as exceptions

def from_dict(data, require=None, use_rsa_signer: bool = True): ...
def from_filename(filename, require=None, use_rsa_signer: bool = True): ...
