from _typeshed import Incomplete
from google.auth import credentials as credentials, exceptions as exceptions

class Credentials(credentials.Credentials):
    token: Incomplete
    def __init__(self, token) -> None: ...
    @property
    def expired(self): ...
    @property
    def valid(self): ...
    def refresh(self, request) -> None: ...
    def apply(self, headers, token=None) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...
