import abc
from dataclasses import dataclass
from google.auth import environment_vars as environment_vars, exceptions as exceptions, external_account as external_account

class RequestSigner:
    def __init__(self, region_name) -> None: ...
    def get_request_options(self, aws_security_credentials, url, method, request_payload: str = '', additional_headers={}): ...

@dataclass
class AwsSecurityCredentials:
    access_key_id: str
    secret_access_key: str
    session_token: str | None = ...

class AwsSecurityCredentialsSupplier(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def get_aws_security_credentials(self, context, request): ...
    @abc.abstractmethod
    def get_aws_region(self, context, request): ...

class _DefaultAwsSecurityCredentialsSupplier(AwsSecurityCredentialsSupplier):
    def __init__(self, credential_source) -> None: ...
    def get_aws_security_credentials(self, context, request): ...
    def get_aws_region(self, context, request): ...

class Credentials(external_account.Credentials):
    def __init__(self, audience, subject_token_type, token_url=..., credential_source=None, aws_security_credentials_supplier=None, *args, **kwargs) -> None: ...
    def retrieve_subject_token(self, request): ...
    @classmethod
    def from_info(cls, info, **kwargs): ...
    @classmethod
    def from_file(cls, filename, **kwargs): ...
