import abc
from _typeshed import Incomplete
from enum import Enum
from google.auth import environment_vars as environment_vars, exceptions as exceptions, metrics as metrics
from google.auth._credentials_base import _BaseCredentials
from google.auth._refresh_worker import RefreshThreadManager as RefreshThreadManager

DEFAULT_UNIVERSE_DOMAIN: str
NO_OP_TRUST_BOUNDARY_LOCATIONS: list[str]
NO_OP_TRUST_BOUNDARY_ENCODED_LOCATIONS: str

class Credentials(_BaseCredentials, metaclass=abc.ABCMeta):
    expiry: Incomplete
    def __init__(self) -> None: ...
    @property
    def expired(self): ...
    @property
    def valid(self): ...
    @property
    def token_state(self): ...
    @property
    def quota_project_id(self): ...
    @property
    def universe_domain(self): ...
    def get_cred_info(self) -> None: ...
    @abc.abstractmethod
    def refresh(self, request): ...
    def apply(self, headers, token=None) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...
    def with_non_blocking_refresh(self) -> None: ...

class CredentialsWithQuotaProject(Credentials, metaclass=abc.ABCMeta):
    def with_quota_project(self, quota_project_id) -> None: ...
    def with_quota_project_from_environment(self): ...

class CredentialsWithTokenUri(Credentials, metaclass=abc.ABCMeta):
    def with_token_uri(self, token_uri) -> None: ...

class CredentialsWithUniverseDomain(Credentials, metaclass=abc.ABCMeta):
    def with_universe_domain(self, universe_domain) -> None: ...

class CredentialsWithRegionalAccessBoundary(Credentials, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @property
    def regional_access_boundary(self): ...
    @property
    def regional_access_boundary_expiry(self): ...
    def with_trust_boundary(self, trust_boundary): ...
    def apply(self, headers, token=None) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...
    def refresh(self, request) -> None: ...

class AnonymousCredentials(Credentials):
    @property
    def expired(self): ...
    @property
    def valid(self): ...
    def refresh(self, request) -> None: ...
    def apply(self, headers, token=None) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...

class ReadOnlyScoped(metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @property
    def scopes(self): ...
    @property
    def default_scopes(self): ...
    @property
    @abc.abstractmethod
    def requires_scopes(self): ...
    def has_scopes(self, scopes): ...

class Scoped(ReadOnlyScoped, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def with_scopes(self, scopes, default_scopes=None): ...

def with_scopes_if_required(credentials, scopes, default_scopes=None): ...

class Signing(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def sign_bytes(self, message): ...
    @property
    @abc.abstractmethod
    def signer_email(self): ...
    @property
    @abc.abstractmethod
    def signer(self): ...

class TokenState(Enum):
    FRESH = 1
    STALE = 2
    INVALID = 3

class CredentialsWithTrustBoundary(CredentialsWithRegionalAccessBoundary, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
