import abc
from dataclasses import dataclass
from google.auth import credentials as credentials, exceptions as exceptions, iam as iam, impersonated_credentials as impersonated_credentials, metrics as metrics
from google.oauth2 import sts as sts, utils as utils

@dataclass
class SupplierContext:
    subject_token_type: str
    audience: str

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri, credentials.CredentialsWithRegionalAccessBoundary, metaclass=abc.ABCMeta):
    def __init__(self, audience, subject_token_type, token_url, credential_source, service_account_impersonation_url=None, service_account_impersonation_options=None, client_id=None, client_secret=None, token_info_url=None, quota_project_id=None, scopes=None, default_scopes=None, workforce_pool_user_project=None, universe_domain=..., trust_boundary=None) -> None: ...
    @property
    def info(self): ...
    @property
    def service_account_email(self): ...
    @property
    def is_user(self): ...
    @property
    def is_workforce_pool(self): ...
    @property
    def requires_scopes(self): ...
    @property
    def project_number(self): ...
    @property
    def token_info_url(self): ...
    def get_cred_info(self): ...
    def with_scopes(self, scopes, default_scopes=None): ...
    @abc.abstractmethod
    def retrieve_subject_token(self, request): ...
    def get_project_id(self, request): ...
    def refresh(self, request) -> None: ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    def with_universe_domain(self, universe_domain): ...
    @classmethod
    def from_info(cls, info, **kwargs): ...
    @classmethod
    def from_file(cls, filename, **kwargs): ...
