from _typeshed import Incomplete
from google.auth import credentials as credentials, exceptions as exceptions, iam as iam
from google.oauth2 import sts as sts, utils as utils

class Credentials(credentials.CredentialsWithQuotaProject, credentials.ReadOnlyScoped, credentials.CredentialsWithTokenUri, credentials.CredentialsWithRegionalAccessBoundary):
    token: Incomplete
    expiry: Incomplete
    def __init__(self, token=None, expiry=None, refresh_token=None, audience=None, client_id=None, client_secret=None, token_url=None, token_info_url=None, revoke_url=None, scopes=None, quota_project_id=None, universe_domain=..., trust_boundary=None) -> None: ...
    @property
    def info(self): ...
    def constructor_args(self): ...
    @property
    def scopes(self): ...
    @property
    def requires_scopes(self): ...
    @property
    def client_id(self): ...
    @property
    def client_secret(self): ...
    @property
    def audience(self): ...
    @property
    def refresh_token(self): ...
    @property
    def token_url(self): ...
    @property
    def token_info_url(self): ...
    @property
    def revoke_url(self): ...
    @property
    def is_user(self): ...
    @property
    def can_refresh(self): ...
    def get_project_id(self, request=None) -> None: ...
    def to_json(self, strip=None): ...
    def revoke(self, request) -> None: ...
    def get_cred_info(self): ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    def with_universe_domain(self, universe_domain): ...
    @classmethod
    def from_info(cls, info, **kwargs): ...
    @classmethod
    def from_file(cls, filename, **kwargs): ...
