import abc
from google.auth import exceptions as exceptions, external_account as external_account
from typing import NamedTuple

class SubjectTokenSupplier(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def get_subject_token(self, context, request): ...

class _TokenContent(NamedTuple):
    content: str
    location: str

class _FileSupplier(SubjectTokenSupplier):
    def __init__(self, path, format_type, subject_token_field_name) -> None: ...
    def get_subject_token(self, context, request): ...

class _UrlSupplier(SubjectTokenSupplier):
    def __init__(self, url, format_type, subject_token_field_name, headers) -> None: ...
    def get_subject_token(self, context, request): ...

class _X509Supplier(SubjectTokenSupplier):
    def __init__(self, trust_chain_path, leaf_cert_callback) -> None: ...
    def get_subject_token(self, context, request): ...

class Credentials(external_account.Credentials):
    def __init__(self, audience, subject_token_type, token_url=..., credential_source=None, subject_token_supplier=None, *args, **kwargs) -> None: ...
    def retrieve_subject_token(self, request): ...
    @classmethod
    def from_info(cls, info, **kwargs): ...
    @classmethod
    def from_file(cls, filename, **kwargs): ...
    def refresh(self, request) -> None: ...
