from _typeshed import Incomplete
from google.auth import credentials as credentials, exceptions as exceptions, iam as iam, jwt as jwt, metrics as metrics

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.Signing, credentials.CredentialsWithRegionalAccessBoundary):
    token: Incomplete
    expiry: Incomplete
    def __init__(self, source_credentials, target_principal, target_scopes, delegates=None, subject=None, lifetime=..., quota_project_id=None, iam_endpoint_override=None, trust_boundary=None) -> None: ...
    def sign_bytes(self, message): ...
    @property
    def signer_email(self): ...
    @property
    def service_account_email(self): ...
    @property
    def signer(self): ...
    @property
    def requires_scopes(self): ...
    def get_cred_info(self): ...
    def with_quota_project(self, quota_project_id): ...
    def with_scopes(self, scopes, default_scopes=None): ...
    @classmethod
    def from_impersonated_service_account_info(cls, info, scopes=None): ...

class IDTokenCredentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, target_credentials, target_audience=None, include_email: bool = False, quota_project_id=None) -> None: ...
    def from_credentials(self, target_credentials, target_audience=None): ...
    def with_target_audience(self, target_audience): ...
    def with_include_email(self, include_email): ...
    def with_quota_project(self, quota_project_id): ...
    token: Incomplete
    expiry: Incomplete
    def refresh(self, request) -> None: ...
