import google.auth.credentials
from google.auth import crypt as crypt, exceptions as exceptions
from google.auth.crypt import es as es

def encode(signer, payload, header=None, key_id=None): ...
def decode_header(token): ...
def decode(token, certs=None, verify: bool = True, audience=None, clock_skew_in_seconds: int = 0): ...

class Credentials(google.auth.credentials.Signing, google.auth.credentials.CredentialsWithQuotaProject):
    def __init__(self, signer, issuer, subject, audience, additional_claims=None, token_lifetime=..., quota_project_id=None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename, **kwargs): ...
    @classmethod
    def from_signing_credentials(cls, credentials, audience, **kwargs): ...
    def with_claims(self, issuer=None, subject=None, audience=None, additional_claims=None): ...
    def with_quota_project(self, quota_project_id): ...
    def refresh(self, request) -> None: ...
    def sign_bytes(self, message): ...
    @property
    def signer_email(self): ...
    @property
    def signer(self): ...
    @property
    def additional_claims(self): ...

class OnDemandCredentials(google.auth.credentials.Signing, google.auth.credentials.CredentialsWithQuotaProject):
    def __init__(self, signer, issuer, subject, additional_claims=None, token_lifetime=..., max_cache_size=..., quota_project_id=None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename, **kwargs): ...
    @classmethod
    def from_signing_credentials(cls, credentials, **kwargs): ...
    def with_claims(self, issuer=None, subject=None, additional_claims=None): ...
    def with_quota_project(self, quota_project_id): ...
    @property
    def valid(self): ...
    def refresh(self, request) -> None: ...
    def before_request(self, request, method, url, headers) -> None: ...
    def sign_bytes(self, message): ...
    @property
    def signer_email(self): ...
    @property
    def signer(self): ...
