from google.auth import version as version

API_CLIENT_HEADER: str
BYOID_HEADER_SECTION: str
REQUEST_TYPE_ACCESS_TOKEN: str
REQUEST_TYPE_ID_TOKEN: str
REQUEST_TYPE_MDS_PING: str
REQUEST_TYPE_REAUTH_START: str
REQUEST_TYPE_REAUTH_CONTINUE: str
CRED_TYPE_USER: str
CRED_TYPE_SA_ASSERTION: str
CRED_TYPE_SA_JWT: str
CRED_TYPE_SA_MDS: str
CRED_TYPE_SA_IMPERSONATE: str

def python_and_auth_lib_version(): ...
def token_request_access_token_mds(): ...
def token_request_id_token_mds(): ...
def token_request_access_token_impersonate(): ...
def token_request_id_token_impersonate(): ...
def token_request_access_token_sa_assertion(): ...
def token_request_id_token_sa_assertion(): ...
def token_request_user(): ...
def mds_ping(): ...
def reauth_start(): ...
def reauth_continue(): ...
def byoid_metrics_header(metrics_options): ...
def add_metric_header(headers, metric_header_value) -> None: ...
