from _typeshed import Incomplete
from google.auth import exceptions as exceptions
from google.auth._credentials_base import _BaseCredentials

class Credentials(_BaseCredentials):
    def __init__(self) -> None: ...
    async def apply(self, headers, token=None) -> None: ...
    async def refresh(self, request) -> None: ...
    async def before_request(self, request, method, url, headers) -> None: ...

class StaticCredentials(Credentials):
    token: Incomplete
    def __init__(self, token) -> None: ...
    async def refresh(self, request) -> None: ...
    async def before_request(self, request, method, url, headers) -> None: ...

class AnonymousCredentials(Credentials):
    async def refresh(self, request) -> None: ...
    async def apply(self, headers, token=None) -> None: ...
    async def before_request(self, request, method, url, headers) -> None: ...
