def session_from_client_config(client_config, scopes, **kwargs): ...
def session_from_client_secrets_file(client_secrets_file, scopes, **kwargs): ...
def credentials_from_session(session, client_config=None): ...
