LOCALHOST: str
DEFAULT_PORTS_TO_TRY: int

def is_port_open(port): ...
def find_open_port(start: int = 8080, stop=None): ...
def get_user_credentials(scopes, client_id, client_secret, minimum_port: int = 8080, maximum_port=None): ...
