import aiohttp
from aiohttp import ClientTimeout as ClientTimeout
from google.auth import exceptions as exceptions
from google.auth.aio import transport as transport
from typing import AsyncGenerator, Mapping

class Response(transport.Response):
    def __init__(self, response: aiohttp.ClientResponse) -> None: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    async def content(self, chunk_size: int = 1024) -> AsyncGenerator[bytes, None]: ...
    async def read(self) -> bytes: ...
    async def close(self) -> None: ...

class Request(transport.Request):
    def __init__(self, session: aiohttp.ClientSession | None = None) -> None: ...
    async def __call__(self, url: str, method: str = 'GET', body: bytes | None = None, headers: Mapping[str, str] | None = None, timeout: float | ClientTimeout = ..., **kwargs) -> transport.Response: ...
    async def close(self) -> None: ...
