import ssl
from google.auth import exceptions as exceptions

def make_client_cert_ssl_context(cert_bytes: bytes, key_bytes: bytes, passphrase: bytes | None = None) -> ssl.SSLContext: ...
def default_client_cert_source(): ...
async def get_client_ssl_credentials(certificate_config_path=None): ...
async def get_client_cert_and_key(client_cert_callback=None): ...
