from _typeshed import Incomplete
from aiohttp import ClientTimeout
from collections.abc import Generator
from contextlib import asynccontextmanager
from google.auth import exceptions as exceptions
from google.auth.aio import transport as transport
from google.auth.aio.credentials import Credentials as Credentials
from google.auth.aio.transport import mtls as mtls
from google.auth.exceptions import TimeoutError as TimeoutError
from typing import Mapping

AIOHTTP_INSTALLED: bool

@asynccontextmanager
async def timeout_guard(timeout) -> Generator[Incomplete, None, Incomplete]: ...

class AsyncAuthorizedSession:
    def __init__(self, credentials: Credentials, auth_request: transport.Request | None = None) -> None: ...
    async def configure_mtls_channel(self, client_cert_callback=None): ...
    async def request(self, method: str, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    async def get(self, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    async def post(self, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    async def put(self, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    async def patch(self, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    async def delete(self, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float = ..., timeout: float | ClientTimeout = ..., total_attempts: int | None = ..., **kwargs) -> transport.Response: ...
    @property
    def is_mtls(self): ...
    async def close(self) -> None: ...
